### ISSUE TITLE
Deprecate version 1.2.4 as it is not a patch release

### ISSUE THREAD

**Issue by jayvdb** [QuickenLoans/ramllint#56]
Could version 1.2.4 be deprecated or unpublished as requested at https://github.com/QuickenLoans/ramllint/pull/52#issuecomment-283554769 .

See https://docs.npmjs.com/cli/deprecate and https://docs.npmjs.com/cli/unpublish .  I dont do much npm work, so I dont know how well those features work, but anyone upgrading to 1.2.4 is up for a large surprise.

Another option could be to create a 1.2.5 release with the problematic feature reverted.

**Comment by kalisjoshua** [comment]
Resolved in #57

**Comment by jayvdb** [comment]
Excuse me, but this is a very different problem.  1.2.4 is not a patch.  It includes new features.
coala has stable releases out in the wild which have a requirement `ramllint~1.2.2` , which means they must use 1.2.x , and the latest version 1.2.4 is still broken.

**Comment by kalisjoshua** [comment]
So you want a 1.2.5 and not a 1.3.1? There was a new feature added in another Pull Request that is what justified the 1.3.0 semver bump; it did introduce a bug and the fix produced 1.3.1. This would mean that the 1.2.x version branch is now deprecated. That is how I understand semver; I could be wrong. I will look into creating a 1.2.5 or deprecating the 1.2.4 version.

**Comment by kalisjoshua** [comment]
So I think I have things squared away now; sorry for the confusion and complication. I have deprecated 1.2.4, 1.2.5, and 1.3.0, in npm - although they are still install-able - and created a new version 1.2.6 which is actually a successor to 1.2.3. I hope this helps with your project. Please let me know if anything else needs attention. Thank you for your help and patience.

**Comment by jayvdb** [comment]
1.3.x is now the default, but 1.2.x is the stable release series.  1.2.x is surely not deprecated merely by the existence of a 1.3.1...?  I havent seen anything like that in the semver description.  But even a deprecated release should not be broken without a good reasons.

In the near future, coala will bump its dependency to `ramllint~1.3.1` or higher, but it is undesirable to need to immediately push out a new patch release of old coala releases to avoid the recent bug.

I very much appreciate that you'll look into getting the 1.2.x back to a sane state, so the old coala releases continue to work correctly.
